# GitHub Labels Configuration for KeneyApp
# Sync with: https://github.com/micnncim/action-label-syncer

# Priority Labels
- name: 'priority: critical'
  color: 'b60205'
  description: 'Critical priority - immediate attention required'

- name: 'priority: high'
  color: 'd93f0b'
  description: 'High priority - should be addressed soon'

- name: 'priority: medium'
  color: 'fbca04'
  description: 'Medium priority - normal queue'

- name: 'priority: low'
  color: '0e8a16'
  description: 'Low priority - can be deferred'

# Type Labels
- name: 'type: bug'
  color: 'd73a4a'
  description: 'Something is not working correctly'

- name: 'type: feature'
  color: 'a2eeef'
  description: 'New feature or enhancement request'

- name: 'type: documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'

- name: 'type: refactor'
  color: 'f9d0c4'
  description: 'Code refactoring without functional changes'

- name: 'type: test'
  color: 'bfdadc'
  description: 'Testing improvements or additions'

- name: 'type: chore'
  color: 'fef2c0'
  description: 'Maintenance tasks and housekeeping'

- name: 'type: security'
  color: 'ee0701'
  description: 'Security-related issues or improvements'

- name: 'type: performance'
  color: 'c5def5'
  description: 'Performance improvements or optimizations'

# Component Labels
- name: 'component: backend'
  color: '5319e7'
  description: 'Backend/API related'

- name: 'component: frontend'
  color: 'bfd4f2'
  description: 'Frontend/UI related'

- name: 'component: database'
  color: 'd4c5f9'
  description: 'Database schema or migrations'

- name: 'component: infrastructure'
  color: 'e99695'
  description: 'Infrastructure, deployment, DevOps'

- name: 'component: ci/cd'
  color: 'bfdadc'
  description: 'CI/CD pipeline and automation'

- name: 'component: security'
  color: 'ee0701'
  description: 'Security components and features'

- name: 'component: fhir'
  color: '0e8a16'
  description: 'FHIR interoperability'

- name: 'component: messaging'
  color: '7057ff'
  description: 'Messaging and notifications'

- name: 'component: documents'
  color: 'fbca04'
  description: 'Document management'

# Status Labels
- name: 'status: needs-triage'
  color: 'ededed'
  description: 'Needs initial review and categorization'

- name: 'status: in-progress'
  color: 'f9d0c4'
  description: 'Work is currently in progress'

- name: 'status: blocked'
  color: 'd93f0b'
  description: 'Blocked by dependencies or decisions'

- name: 'status: needs-review'
  color: 'fbca04'
  description: 'Waiting for code review'

- name: 'status: needs-info'
  color: 'd876e3'
  description: 'Waiting for more information'

- name: 'status: ready-for-merge'
  color: '0e8a16'
  description: 'Approved and ready to merge'

# Workflow Labels
- name: 'good first issue'
  color: '7057ff'
  description: 'Good for newcomers to the project'

- name: 'help wanted'
  color: '008672'
  description: 'Extra attention or help is needed'

- name: 'breaking change'
  color: 'b60205'
  description: 'Breaking API or behavior change'

- name: 'dependencies'
  color: '0366d6'
  description: 'Dependency updates'

- name: 'duplicate'
  color: 'cfd3d7'
  description: 'This issue or PR already exists'

- name: 'invalid'
  color: 'e4e669'
  description: 'This does not seem right or valid'

- name: 'wontfix'
  color: 'ffffff'
  description: 'This will not be worked on'

- name: 'stale'
  color: 'ededed'
  description: 'No recent activity'

- name: 'keep-open'
  color: '0e8a16'
  description: 'Exempt from stale bot'

- name: 'roadmap'
  color: 'ffaac3'
  description: 'Part of the project roadmap'

# Healthcare/Compliance Labels
- name: 'compliance: gdpr'
  color: '1d76db'
  description: 'GDPR compliance related'

- name: 'compliance: hipaa'
  color: '5319e7'
  description: 'HIPAA compliance related'

- name: 'compliance: hds'
  color: '0e8a16'
  description: 'French HDS certification related'

- name: 'healthcare: french'
  color: '0052cc'
  description: 'French healthcare standards (INS, MSSanté, etc.)'

# Size Labels (for PRs)
- name: 'size: XS'
  color: '009900'
  description: 'Extra small PR (1-10 lines)'

- name: 'size: S'
  color: '77cc00'
  description: 'Small PR (11-50 lines)'

- name: 'size: M'
  color: 'eebb00'
  description: 'Medium PR (51-200 lines)'

- name: 'size: L'
  color: 'ff9900'
  description: 'Large PR (201-500 lines)'

- name: 'size: XL'
  color: 'ff0000'
  description: 'Extra large PR (500+ lines)'
