"""add_notification_tables

Revision ID: 496bc14415db
Revises: 018_add_ins_to_patients
Create Date: 2025-11-30 15:38:54.902675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '496bc14415db'
down_revision = '018_add_ins_to_patients'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_notification_tenant_created'), table_name='notifications')
    op.drop_index(op.f('idx_notification_type_status'), table_name='notifications')
    op.drop_index(op.f('idx_notification_user_created'), table_name='notifications')
    op.drop_index(op.f('idx_notification_user_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_dmp_integration_dmp_id'), table_name='dmp_integration')
    op.drop_index(op.f('ix_dmp_integration_patient_id'), table_name='dmp_integration')
    op.drop_index(op.f('ix_dmp_integration_tenant_id'), table_name='dmp_integration')
    op.drop_table('dmp_integration')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_healthcare_professional_cps_adeli_number'), table_name='healthcare_professional_cps')
    op.drop_index(op.f('ix_healthcare_professional_cps_cps_number'), table_name='healthcare_professional_cps')
    op.drop_index(op.f('ix_healthcare_professional_cps_rpps_number'), table_name='healthcare_professional_cps')
    op.drop_index(op.f('ix_healthcare_professional_cps_tenant_id'), table_name='healthcare_professional_cps')
    op.drop_index(op.f('ix_healthcare_professional_cps_user_id'), table_name='healthcare_professional_cps')
    op.drop_table('healthcare_professional_cps')
    op.drop_index(op.f('ix_patient_ins_ins_number'), table_name='patient_ins')
    op.drop_index(op.f('ix_patient_ins_patient_id'), table_name='patient_ins')
    op.drop_index(op.f('ix_patient_ins_tenant_id'), table_name='patient_ins')
    op.drop_table('patient_ins')
    op.drop_index(op.f('ix_subscriptions_criteria_prefix'), table_name='subscriptions', postgresql_ops={'criteria': 'text_pattern_ops'})
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tenant_status'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_mssante_messages_internal_message_id'), table_name='mssante_messages')
    op.drop_index(op.f('ix_mssante_messages_mssante_message_id'), table_name='mssante_messages')
    op.drop_index(op.f('ix_mssante_messages_tenant_id'), table_name='mssante_messages')
    op.drop_table('mssante_messages')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_tenant_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_constraint(op.f('fk_appointments_tenant_id'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'tenants', ['tenant_id'], ['id'])
    op.add_column('lab_test_criteria', sa.Column('code', sa.String(length=64), nullable=True))
    op.add_column('lab_test_criteria', sa.Column('test_method', sa.String(length=128), nullable=True))
    op.add_column('lab_test_criteria', sa.Column('normal_range', sa.String(length=128), nullable=True))
    op.add_column('lab_test_criteria', sa.Column('warning', sa.Boolean(), nullable=True))
    op.add_column('lab_test_criteria', sa.Column('limits_verified', sa.Boolean(), nullable=True))
    op.add_column('lab_test_criteria', sa.Column('excluded', sa.Boolean(), nullable=True))
    op.add_column('lab_test_criteria', sa.Column('to_integer', sa.Boolean(), nullable=True))
    op.add_column('lab_test_criteria', sa.Column('sequence', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lab_test_criteria_code'), 'lab_test_criteria', ['code'], unique=False)
    op.create_index(op.f('ix_lab_test_criteria_id'), 'lab_test_criteria', ['id'], unique=False)
    op.add_column('lab_test_types', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('lab_test_types', 'category',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('HEMATOLOGY', 'FLUID_EXCRETA', 'BIOCHEMICAL', 'IMMUNOLOGICAL', 'MICROBIOLOGICAL', 'MOLECULAR_BIOLOGY', 'CHROMOSOME_GENETIC', 'OTHERS', name='labtestcategory'),
               existing_nullable=True)
    op.alter_column('lab_test_types', 'report_style',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('TABLE_WITH_UNITS', 'TABLE_WITH_RANGE', 'TABLE_RESULT_ONLY', 'TABLE_NO_HEADER', 'TABLE_NO_HEADER_IMG', 'NO_TABLE', 'DO_NOT_SHOW', name='labreportstyle'),
               existing_nullable=True)
    op.create_index(op.f('ix_lab_test_types_category'), 'lab_test_types', ['category'], unique=False)
    op.create_index(op.f('ix_lab_test_types_id'), 'lab_test_types', ['id'], unique=False)
    op.alter_column('medical_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('medical_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_medical_documents_checksum'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_created_at'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_patient_deleted'), table_name='medical_documents')
    op.drop_index(op.f('ix_medical_documents_patient_type'), table_name='medical_documents')
    op.drop_constraint(op.f('medical_documents_patient_id_fkey'), 'medical_documents', type_='foreignkey')
    op.drop_constraint(op.f('medical_documents_uploaded_by_id_fkey'), 'medical_documents', type_='foreignkey')
    op.drop_constraint(op.f('medical_documents_prescription_id_fkey'), 'medical_documents', type_='foreignkey')
    op.drop_constraint(op.f('medical_documents_appointment_id_fkey'), 'medical_documents', type_='foreignkey')
    op.create_foreign_key(None, 'medical_documents', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'medical_documents', 'users', ['uploaded_by_id'], ['id'])
    op.create_foreign_key(None, 'medical_documents', 'appointments', ['appointment_id'], ['id'])
    op.create_foreign_key(None, 'medical_documents', 'prescriptions', ['prescription_id'], ['id'])
    op.alter_column('medical_record_shares', 'scope',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('FULL_RECORD', 'APPOINTMENTS_ONLY', 'PRESCRIPTIONS_ONLY', 'DOCUMENTS_ONLY', 'CUSTOM', name='sharescope', native_enum=False),
               existing_nullable=False)
    op.alter_column('medical_record_shares', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', 'USED', name='sharestatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('medical_record_shares', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('medical_record_shares', 'last_accessed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('medical_record_shares', 'consent_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('medical_record_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('medical_record_shares', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('medical_record_shares', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_medical_record_shares_active'), table_name='medical_record_shares')
    op.drop_constraint(op.f('medical_record_shares_patient_id_fkey'), 'medical_record_shares', type_='foreignkey')
    op.drop_constraint(op.f('medical_record_shares_revoked_by_user_id_fkey'), 'medical_record_shares', type_='foreignkey')
    op.drop_constraint(op.f('medical_record_shares_shared_by_user_id_fkey'), 'medical_record_shares', type_='foreignkey')
    op.create_foreign_key(None, 'medical_record_shares', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'medical_record_shares', 'users', ['revoked_by_user_id'], ['id'])
    op.create_foreign_key(None, 'medical_record_shares', 'users', ['shared_by_user_id'], ['id'])
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_messages_conversation'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_unread'), table_name='messages')
    op.drop_constraint(op.f('messages_receiver_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_reply_to_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(op.f('fk_patients_tenant_id'), 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('fk_prescriptions_tenant_id'), 'prescriptions', type_='foreignkey')
    op.create_foreign_key(None, 'prescriptions', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('tenant_modules', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_tenant_modules_id'), 'tenant_modules', ['id'], unique=False)
    op.drop_constraint(op.f('tenant_modules_tenant_id_fkey'), 'tenant_modules', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_modules', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('tenants', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('uq_tenants_slug'), 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_index(op.f('ix_users_is_locked'), table_name='users')
    op.drop_index(op.f('ix_users_mfa_enabled'), table_name='users')
    op.drop_constraint(op.f('fk_users_tenant_id'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_tenant_id'), 'users', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_users_mfa_enabled'), 'users', ['mfa_enabled'], unique=False)
    op.create_index(op.f('ix_users_is_locked'), 'users', ['is_locked'], unique=False)
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_tenants_slug'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'configuration',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'tenant_modules', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_modules_tenant_id_fkey'), 'tenant_modules', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tenant_modules_id'), table_name='tenant_modules')
    op.alter_column('tenant_modules', 'configuration',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_prescriptions_tenant_id'), 'prescriptions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key(op.f('fk_patients_tenant_id'), 'patients', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_reply_to_id_fkey'), 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('messages_receiver_id_fkey'), 'messages', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_messages_receiver_unread'), 'messages', ['receiver_id', 'read_at', 'tenant_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation'), 'messages', ['sender_id', 'receiver_id', 'created_at'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'medical_record_shares', type_='foreignkey')
    op.drop_constraint(None, 'medical_record_shares', type_='foreignkey')
    op.drop_constraint(None, 'medical_record_shares', type_='foreignkey')
    op.create_foreign_key(op.f('medical_record_shares_shared_by_user_id_fkey'), 'medical_record_shares', 'users', ['shared_by_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('medical_record_shares_revoked_by_user_id_fkey'), 'medical_record_shares', 'users', ['revoked_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('medical_record_shares_patient_id_fkey'), 'medical_record_shares', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_medical_record_shares_active'), 'medical_record_shares', ['status', 'expires_at'], unique=False)
    op.alter_column('medical_record_shares', 'revoked_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('medical_record_shares', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('medical_record_shares', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('medical_record_shares', 'consent_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('medical_record_shares', 'last_accessed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('medical_record_shares', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('medical_record_shares', 'status',
               existing_type=sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', 'USED', name='sharestatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('medical_record_shares', 'scope',
               existing_type=sa.Enum('FULL_RECORD', 'APPOINTMENTS_ONLY', 'PRESCRIPTIONS_ONLY', 'DOCUMENTS_ONLY', 'CUSTOM', name='sharescope', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'medical_documents', type_='foreignkey')
    op.drop_constraint(None, 'medical_documents', type_='foreignkey')
    op.drop_constraint(None, 'medical_documents', type_='foreignkey')
    op.drop_constraint(None, 'medical_documents', type_='foreignkey')
    op.create_foreign_key(op.f('medical_documents_appointment_id_fkey'), 'medical_documents', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('medical_documents_prescription_id_fkey'), 'medical_documents', 'prescriptions', ['prescription_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('medical_documents_uploaded_by_id_fkey'), 'medical_documents', 'users', ['uploaded_by_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('medical_documents_patient_id_fkey'), 'medical_documents', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_medical_documents_patient_type'), 'medical_documents', ['patient_id', 'document_type', 'tenant_id'], unique=False)
    op.create_index(op.f('ix_medical_documents_patient_deleted'), 'medical_documents', ['patient_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_medical_documents_created_at'), 'medical_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_medical_documents_checksum'), 'medical_documents', ['checksum'], unique=False)
    op.alter_column('medical_documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('medical_documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_lab_test_types_id'), table_name='lab_test_types')
    op.drop_index(op.f('ix_lab_test_types_category'), table_name='lab_test_types')
    op.alter_column('lab_test_types', 'report_style',
               existing_type=sa.Enum('TABLE_WITH_UNITS', 'TABLE_WITH_RANGE', 'TABLE_RESULT_ONLY', 'TABLE_NO_HEADER', 'TABLE_NO_HEADER_IMG', 'NO_TABLE', 'DO_NOT_SHOW', name='labreportstyle'),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('lab_test_types', 'category',
               existing_type=sa.Enum('HEMATOLOGY', 'FLUID_EXCRETA', 'BIOCHEMICAL', 'IMMUNOLOGICAL', 'MICROBIOLOGICAL', 'MOLECULAR_BIOLOGY', 'CHROMOSOME_GENETIC', 'OTHERS', name='labtestcategory'),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('lab_test_types', 'description')
    op.drop_index(op.f('ix_lab_test_criteria_id'), table_name='lab_test_criteria')
    op.drop_index(op.f('ix_lab_test_criteria_code'), table_name='lab_test_criteria')
    op.drop_column('lab_test_criteria', 'sequence')
    op.drop_column('lab_test_criteria', 'to_integer')
    op.drop_column('lab_test_criteria', 'excluded')
    op.drop_column('lab_test_criteria', 'limits_verified')
    op.drop_column('lab_test_criteria', 'warning')
    op.drop_column('lab_test_criteria', 'normal_range')
    op.drop_column('lab_test_criteria', 'test_method')
    op.drop_column('lab_test_criteria', 'code')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_appointments_tenant_id'), 'appointments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_appointment_reminders', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_lab_results', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_prescription_renewals', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_messages', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_documents', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('email_system_alerts', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sms_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sms_appointment_reminders', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sms_lab_results', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sms_prescription_renewals', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sms_messages', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('push_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('push_appointment_reminders', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('push_lab_results', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('push_prescription_renewals', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('push_messages', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('push_documents', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('websocket_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_start', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_end', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('notification_preferences_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_preferences_pkey'))
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_index(op.f('ix_notification_preferences_tenant_id'), 'notification_preferences', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_table('mssante_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('internal_message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mssante_message_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sender_mssante_address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('receiver_mssante_address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('has_attachments', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('attachment_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['internal_message_id'], ['messages.id'], name=op.f('mssante_messages_internal_message_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('mssante_messages_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mssante_messages_pkey')),
    sa.UniqueConstraint('mssante_message_id', name=op.f('mssante_messages_mssante_message_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mssante_messages_tenant_id'), 'mssante_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mssante_messages_mssante_message_id'), 'mssante_messages', ['mssante_message_id'], unique=False)
    op.create_index(op.f('ix_mssante_messages_internal_message_id'), 'mssante_messages', ['internal_message_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'requested'::character varying"), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('criteria', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('channel_type', sa.VARCHAR(length=30), server_default=sa.text("'rest-hook'::character varying"), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('payload', sa.VARCHAR(length=128), server_default=sa.text("'application/fhir+json'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('subscriptions_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey'))
    )
    op.create_index(op.f('ix_subscriptions_tenant_status'), 'subscriptions', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_criteria_prefix'), 'subscriptions', ['criteria'], unique=False, postgresql_ops={'criteria': 'text_pattern_ops'})
    op.create_table('patient_ins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ins_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('nir_key', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('oid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'verified', 'failed', 'expired', name='insstatus'), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verification_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('verification_operator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('birth_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('first_names', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('birth_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('birth_location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('birth_location_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('gender_code', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_check_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('patient_ins_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('patient_ins_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['verification_operator_id'], ['users.id'], name=op.f('patient_ins_verification_operator_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patient_ins_pkey')),
    sa.UniqueConstraint('ins_number', name=op.f('patient_ins_ins_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('patient_id', name=op.f('patient_ins_patient_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_patient_ins_tenant_id'), 'patient_ins', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_patient_ins_patient_id'), 'patient_ins', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_ins_ins_number'), 'patient_ins', ['ins_number'], unique=False)
    op.create_table('healthcare_professional_cps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cps_type', postgresql.ENUM('cps', 'e_cps', 'cpf', name='cpstype'), autoincrement=False, nullable=False),
    sa.Column('cps_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('rpps_number', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('adeli_number', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('profession_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('profession_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('specialty_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('specialty_label', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('practice_structure_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('practice_structure_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('psc_sub', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('psc_token_endpoint', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('psc_last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('issue_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('healthcare_professional_cps_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('healthcare_professional_cps_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('healthcare_professional_cps_pkey')),
    sa.UniqueConstraint('cps_number', name=op.f('healthcare_professional_cps_cps_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('psc_sub', name=op.f('healthcare_professional_cps_psc_sub_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('healthcare_professional_cps_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_healthcare_professional_cps_user_id'), 'healthcare_professional_cps', ['user_id'], unique=False)
    op.create_index(op.f('ix_healthcare_professional_cps_tenant_id'), 'healthcare_professional_cps', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_healthcare_professional_cps_rpps_number'), 'healthcare_professional_cps', ['rpps_number'], unique=False)
    op.create_index(op.f('ix_healthcare_professional_cps_cps_number'), 'healthcare_professional_cps', ['cps_number'], unique=False)
    op.create_index(op.f('ix_healthcare_professional_cps_adeli_number'), 'healthcare_professional_cps', ['adeli_number'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('dmp_integration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dmp_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dmp_consent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('dmp_consent_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('dmp_access_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('documents_sent_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('documents_received_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('dmp_integration_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('dmp_integration_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dmp_integration_pkey')),
    sa.UniqueConstraint('dmp_id', name=op.f('dmp_integration_dmp_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_dmp_integration_tenant_id'), 'dmp_integration', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dmp_integration_patient_id'), 'dmp_integration', ['patient_id'], unique=False)
    op.create_index(op.f('ix_dmp_integration_dmp_id'), 'dmp_integration', ['dmp_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('APPOINTMENT_REMINDER', 'APPOINTMENT_CONFIRMED', 'APPOINTMENT_CANCELLED', 'LAB_RESULTS_READY', 'PRESCRIPTION_RENEWAL', 'MESSAGE_RECEIVED', 'DOCUMENT_SHARED', 'DOCUMENT_UPLOADED', 'SYSTEM_ALERT', 'SECURITY_ALERT', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('channel', postgresql.ENUM('EMAIL', 'SMS', 'PUSH', 'WEBSOCKET', name='notificationchannel'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'READ', name='notificationstatus'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('recipient_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recipient_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('failed_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('notifications_tenant_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('idx_notification_user_status'), 'notifications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_notification_user_created'), 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_notification_type_status'), 'notifications', ['type', 'status'], unique=False)
    op.create_index(op.f('idx_notification_tenant_created'), 'notifications', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
